name = "umg-frontend"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
NEXT_PUBLIC_API_URL = "https://api.mahajanga-univ.mg/api/v1"
NEXT_PUBLIC_SITE_URL = "https://mahajanga-univ.mg"
NEXT_PUBLIC_GOOGLE_VERIFICATION = "HSi9ls6A8pKdn4SmPoB8CBWaDND1uXNnmWOpivLT2xA"
ADMIN_HOSTS = "back.mahajanga-univ.mg,admin.mahajanga-univ.mg"
PUBLIC_HOSTS = "mahajanga-univ.mg,www.mahajanga-univ.mg"